UKHomeOffice/explosives-precursors-poisons

apps/epp-amend/behaviours/licence-validator.js, apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json
Create a what is YOUR DOB page for amend path section 3
as per jira ticket request [EPP-58](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-58) 
- add field in fields/index.js, page.json, fields.json and validation.json
- add steps in summary-data-sections.js
manual
=> EPP-58 Create a what is YOUR DOB page for Amend

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/confirm.html, apps/epp-new/views/partials/summary-table.html, apps/epp-renew/translations/src/en/pages.json
[EPP-46](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-46) - New & Renew - Create a CONTACT DETAILS page.
To Allow user enter new contact detail
- Added Fields for each method of contact in the fields folder and applied the validation control on each fields
- Added title page
- Created a partial page for the confirm summary page then added the values of each fields
- Added page header and content according to figma design.
Tested locally
=> EPP-46 New & Renew Create contact detail page

README.md, apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/journey.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, config.js, hof.settings.json, package.json
Added `what is your name` page in amend path section 2
As per jira ticket [EPP-57](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-57)
- add fields in `fields/index.js`, `fields.json`, `page.json`,` validation.json`
- add step and fields in `summary-data-sections.js`
- defined steps in `index.js`
manual test
- add some logic to render fields in confirm-summary page
- correct service name "Explosives precursors and poisons"
- add `confirm.html`file,
- update steps and fields in `summary-data-sections.js`
- add fields for the confirm summary page in `pages.json`
- add initial page path for this section in `apps/epp-common/index.js`
- correct date format for `date of birth`
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b5009 …
=> EPP-57 Amend - SEC2 - Create a what is YOUR NAME on the licence page

apps/epp-new/behaviours/section-counter.js, apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/medical-history.html
Create a YOUR MEDICAL HISTORY page
as per business request specified in jira ticket [EPP-75](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-75)
add new fields :
* `new-renew-has-seen-doctor`
* `new-renew-received-treatment`
in the following files:
- index.js
- fields/index.js
- page.json
- validation.json
- fields.json
- create `medical-history.html`
- add steps in `summary data stections`
- add logic if `new-renew-received-treatment` value is "yes" redirect to `/new-renew/medical-form`
- add "continueOnEdit" property to keep the redirection to medical form page incase response change from "no" to "yes" when edit from confirm page
manual
=> EPP-75-newRenew-medical-history

config.js
[EPP-115](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-115) - Setup notify templates
Notify templates are created for prod and not prod. 
- Prod and not prod template created
- hof-service-config updated with the template ids - https://github.com/UKHomeOfficeForms/hof-services-config/pull/447
- template ids are updated in service-secrets 
=> EPP-115 Configure Notify template ids

.drone.yml, kube/html-pdf/html-pdf-deployment.yml, kube/html-pdf/html-pdf-network-policy.yml, kube/html-pdf/html-pdf-service.yml
* The current email to users contains the form data in the email but also a pdf attachment.
* system design is similar to the Firearms service
* EPP is using the Image tags of recent services like FMR
* https://collaboration.homeoffice.gov.uk/jira/browse/EPP-159
* Rearrange order of Drone Steps execution
* HTML is rendered and sent as PDF attachment using this microservice
* Service, Ingress and depoyments are created with the added files
* Once the form is completed and tested. Upon Submitting the form we expect to receive an email using gov notify key to hof test email box. Then we can validate and make any changes further
=> EPP-159: Add HTML-PDF-CONVERTER deployment to EPP

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/countersignatory-details.html, test/unit/utilities/utilities.spec.js, utilities/helpers/index.js
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-91 - COUNTERSIGNATORY DETAILS page
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-92 - COUNTERSIGNATORY ADDRESS page
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-93 - COUNTERSIGNATORY CONTACT DETAILS page
EPP-91, EPP-92 & EPP-93 are combined into a single PR because they are closely related, have similar implementation logic, and don’t involve significant complexity or risk of conflicts. Grouping them together minimizes redundant reviews, and duplicate code effort. 
- Pages are created based on the figma and ACs
- countersignatoryYears list is used from constants to show the drop down items
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262 …
=> EPP-91, 92, 93 - countersignatory details, address, contact details pages

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json
create identity details page to allow user to choose which type of proof of identity wants to provide
as per request in jira ticket [EPP-47](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-47)
Add new fields to 
- fields/index.js, 
- index, pages.json, 
- fields.json, 
- validation.json
manual test
=> EPP-47 add identity details page new and renew

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/select-precursor.html
[EPP-132](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-132) - Amend - SEC15 - Create a SELECT PRECURSOR page.
Allow user to select from provided options.
- Added select-precursor.html page to render content according to figma design .
- Added validation control and error message.
- Added fields.
- Added selected value to confirm page
Tested manually 
=> EPP 132 Create select precursor page

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, config.js
[EPP-41](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-41) - Create previous address page for new & renew flow - EPP
Allows user to add a previous address
- Added Heading and radio buttons for page
=> EPP-41 Create previous address page

apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/buttons.json, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/upload-british-passport.html, config.js
Add British passport upload page as per jira ticket request [EPP-102](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-102)
to give the user the possibility to upload their proof of identity
- add field for upload input in:
- summary-data-sections.js
- buttons.json
- field.json
- pages.json
- validation.json
- upload-british-passport.html
- add limitation in config.js file
- add button
n/a
=> EPP-102 Amend path UPLOAD BRITISH PASSPORT

apps/epp-amend/translations/src/en/journey.json, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/journey.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/upload-passport.html, apps/epp-renew/translations/src/en/journey.json, apps/epp-replace/translations/src/en/journey.json, config.js
[EPP-49](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-49) - New & Renew - Create a UPLOAD PASSPORT page
- File upload page has been created for EU passport
- Added custom html page
- errors and config is defined
=> EPP-49 Upload EU Passport Page

apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/upload-british-passport.html, apps/epp-new/views/upload-proof-address.html, config.js
[EPP-45](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-45) - New & Renew - Create a UPLOAD PROOF OF ADDRESS page
Created upload proof of address page so users can upload their proof of address
=> EPP-45 Upload address proof page

apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/journey.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/upload-passport.html, config.js
add upload (EU) passport page as per jira ticket [EPP-103](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-103)
to allow user to upload other type of passport like EU, Switzerland, Norway, Iceland or Liechtenstein.
configured the following files as follows: 
- add create html for upload passport
- add content in pages.json
- add section in summary-data-section
- update index.js with the new page
- add in validation.json and config.js max limit error message in case limit increase more than 1.
- fixed some typos for British passport page
manual test on local
=> Epp 103 upload (EU) passport

apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/upload-driving-licence.html, config.js
add upload (EU) passport page as per jira ticket [EPP-104](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-104)
to allow user to upload other type of identification document such driving licence
configured the following files as follows: 
- add create html for upload passport
- add content in pages.json
- add section in summary-data-section
- update index.js with the new page
- add in validation.json and config.js max limit error message in case limit increase more than 1.
manual test on local
=> EPP-104 UPLOAD UK DRIVING LICENCE

apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/upload-driving-licence.html, config.js
[EPP-50](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-50) - Create upload driving licence page for new & renew flow - EPP
Allows user to upload a form of identification (driving licence)
- implementation of upload functionality
=> EPP-50 create upload driving licence page

apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/upload-certificate-conduct.html, config.js
As per Jira ticket [EPP-105](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-105) created "upload certificate of good conduct"  in the amend user journey.
to allow user to update documents to prove the good conduct. 
- add new field in index.js, pages.json and summay-data-section.js
- add upload-certificate-conduct.html file
- update validation.json and config.file to handle file upload limits
manual test
=> EPP-105 amend create upload certificate of good conduct

apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/upload-proof-address.html, config.js
add upload proof of address page as per jira ticket [EPP-119](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-119)
to allow user to upload documents that prove their residency
configured the following files as follows:
- add create html for upload passport
- add content in pages.json
- add section in summary-data-section
- update index.js with the new page
- add in validation.json and config.js max limit error message in case limit increase more than 2.
manual test
=> EPP-119-amend-UPLOAD-PROOF-OF-ADDRESS

apps/epp-amend/index.js, apps/epp-amend/translations/src/en/pages.json, apps/epp-common/behaviours/dob-edit-redirect.js, apps/epp-new/index.js, test/unit/behaviours/dob-edit-redirect.spec.js, test/unit/utilities/utilities.spec.js, utilities/helpers/index.js
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-163 - Amend - Edit Journey for DOB page
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-164 - New & Renew - Edit Journey for DOB page
EPP-163 & EPP-164 are combined into a single PR because they are using the same behaviour and have same implementation logic. Grouping them together minimise redundant reviews, and duplicate code effort.
New behaviour has been added to validate the date and redirect if required
Helper is created to verify the edit journey
=> EPP-163, 164 Under 18 Redirection - Edit Journey

apps/epp-new/index.js
[EPP-229](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-229) - Routing logic for home address page
After the design change, if the moved date no longer meets the 'more than 5 year' condition then the user should progress to the previous-address page.
Routing is updated to /previous-address
=> EPP-229 Routing Update

apps/epp-amend/index.js, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/upload-british-passport.html, apps/epp-amend/views/upload-certificate-conduct.html, apps/epp-amend/views/upload-driving-licence.html, apps/epp-amend/views/upload-passport.html, apps/epp-amend/views/upload-proof-address.html, apps/epp-common/behaviours/save-document.js, apps/epp-common/behaviours/uploaded-files-counter.js, apps/epp-new/index.js, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/birth-certificate.html, apps/epp-new/views/medical-form.html, apps/epp-new/views/upload-british-passport.html, apps/epp-new/views/upload-certificate-conduct.html, apps/epp-new/views/upload-driving-licence.html, apps/epp-new/views/upload-passport.html, apps/epp-new/views/upload-proof-address.html, apps/epp-replace/index.js, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/upload-british-passport.html, apps/epp-replace/views/upload-certificate-conduct.html, apps/epp-replace/views/upload-driving-licence.html, apps/epp-replace/views/upload-passport.html, apps/epp-replace/views/upload-proof-address.html, test/unit/behaviours/uploaded-files-counter.spec.js
[EPP-227](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-227) - File upload number counter and minimum validation
- File upload component improvement and accessibility bug
- Updated file counter for pages require more than 1 file to be uploaded
- fixed accessibility bug with adding visually hidden text
=> EPP-227 File counter and min files error

apps/epp-amend/index.js, apps/epp-common/behaviours/delete-redundant-documents.js, apps/epp-new/index.js, apps/epp-replace/index.js, test/unit/behaviours/delete-redundant-documents.spec.js
[EPP-243](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-243)- Uploaded document still visible in summary page
An issue has been identified where upload documents are still visible after the related fields are updated from yes to no. 
- Behaviour is added to delete the redundant documents
- TODO added in the replace flow so it can be addressed when we build the replace flow
=> EPP-243 Remove redundant upload docs

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-common/behaviours/dob-under18-redirect.js
create countersignatory-id page as per jira ticket [EPP-155](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-155)
To  give the opportunity, to the user to provide the countersignatory document number.
- add fields in index.js, fields/index.js field.json, pages.jon and validation.json
- add section in summary-data-sections.js
manual
=> EPP-155 countersignatory-id

README.md, apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/change-substances.html, apps/epp-common/behaviours/check-answer-redirect.js, test/unit/behaviours/check-answer-redirect.spec.js
as per jira ticket [EPP-146](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-146) Create a CHANGE SUBSTANCES page 
to allow the user to be directed to change substance flow or to skip this step
- add change-substances.html
- add fields in index.js, fields.json and pages.json and fiels/index.js
- add summary-data-section.js
- add some path to next page
n/a manual
=> EPP-146 amend CHANGE SUBSTANCES page

apps/epp-amend/index.js, apps/epp-common/index.js, apps/epp-new/behaviours/check-back-link.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-renew/index.js, apps/epp-replace/index.js, test/unit/behaviours/check-back-link.spec.js, test/unit/behaviours/get-payment-info.spec.js, test/unit/behaviours/initiate-payment-request.spec.js, test/unit/utilities/api.spec.js, test/unit/utilities/utilities.spec.js, utilities/constants/string-constants.js, utilities/helpers/api.js
- Update base url for new and renew forms from `/new-and-renew` to `/new-renew `
- Added Journey Validator to protect routes
Business/UCD suggested to update the base path /new-renew as its clear and concise 
Path is changed across the application
tested locally
=> EPP-223 Updated base path - New Renew

apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/birth-certificate.html, config.js
create upload birth certificate for replace journey as per jira ticket [EPP-212](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-212)
to give  the user the opportunity to upload a birth certificate file
- add birth-certificate.html upload page
- update page.json, validation.json, index.js and summary-data-sections.js
manual test
currently this element is not visible in the confirmation summary page, since the conditional statement used to retrieve and display the value will be always false since date or birth page is not child  yet.
=> EPP-212 replace upload Birth Certificate

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/poisons.html, apps/epp-common/behaviours/check-answer-redirect.js
create regulated poisons page as per jira ticket [EPP-168](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-168)
to give user the possibility to select if want to add poisons to the licence
- add fields/index.js, fields.json, pages.json, validation.js
- add poisons.html
- update index.js
- update summary-data-section.js
- update check-answer-redirect.js
will be added after merging PR [76](https://github.com/UKHomeOffice/explosives-precursors-poisons/pull/76) is merged since `check-answer-redirect.js` belongs to that change
=> EPP-168 REGULATED POISONS

apps/epp-amend/fields/index.js, apps/epp-amend/translations/src/en/validation.json, apps/epp-new/fields/index.js, apps/epp-new/translations/src/en/validation.json
[EPP-249](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-249) - Contact Phone Number Accepts Letters
The phone number field allows letters, but it should only accept numerical values.
Validation is updated using the existing custom tel number validator
local and branch testing
=> EPP-249 Telephone number validation

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json
create a Countersignatory ID type and number page as per jira ticket [EPP-210](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-210)
to give user opportunity to select preferred document type and provide its number
- add new fields in fields/index.js, , fields.json, pages.json, validation.json 
- update index.js
- update summary-data-sections.js
=> EPP-210 replace countersignatory ID

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json
[EPP-190](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-190) - Create identity details page for Replace - EPP
Allows user to enter which identity they would like to use and the information
=> EPP-190 create identity details page

apps/epp-amend/index.js, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/views/no-details-amend.html, apps/epp-common/behaviours/check-answer-redirect.js, apps/epp-common/behaviours/set-backlink.js
Create no details amend page as per jira ticket [EPP-174](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-174)
To redirect user in case of negative responses for "name", "address", and "substances".
- add no-details-amend.html page
- add content in templates pages.json
I also create a behaviour to set the back link for redirection from different pages reusable also for different redirection paths:
- add set-backLink.js
- update check-answer-redirect and index.js
manual test
=> EPP-174 no details amend page

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/no-poisons-or-precursors.html
create a page to inform user that no change will be applied to the poisons or precursor licence as per jira ticket 
[EPP-175](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-175)
This page allows user to return to initial question of change substance if `yes` is selected and go again to the substances change section.
- add field and ford to index.js
- add new field to fields/index.js, pages.json, fields.json, validation.json
- add no-poisons-or-precursors.html page
manual test
=> EPP-175 not change page

apps/epp-replace/index.js
[EPP-278](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-278) - Added section number to home address page (section 6) for Replace - EPP
Section number was not added in previous ticket (EPP-186)
Added section number in the index file.
=> EPP-278 BUG - added section number to home address for replace

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-common/behaviours/aggregator-save-update-precursors-poisons.js, apps/epp-common/behaviours/render-poison-detail.js, apps/epp-common/behaviours/render-precursors-detail.js, test/unit/behaviours/aggregator-save-update-precursors-poisons.spec.js, test/unit/utilities/utilities.spec.js, utilities/constants/string-constants.js, utilities/helpers/index.js
Create a poison details page as per jira ticket [EPP-170](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-170)
to allow user to provide details about the poison on the licence that needs to be amended
- add `fields` for poison details page in 
- `index.js`, 
- `fields/index.js`, 
- ` fields.json`, 
- `page,json`, 
-`validation.json`
- update `utilities/helpers/index.js` with custom trimming method for poison
- create behaviour `render-poison-detail.js` to render poison's details
manual
**NB** the confirm summary page will be worked in ticket EPP-172, since this page has a mid-journey summary page (`poisons-summary page`). 
=> Epp-170  Poison Details page for amend flow

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-common/behaviours/aggregator-save-update-precursors-poisons.js, apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/validation.json, apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/select-precursor.html
[EPP-200](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-200) -  Replace SELECT PRECURSOR page
To allow users to select a precursor from the drop down list
- Page is created with required validation and content
- Renamed the field name across 4 forms for reusability 
=> EPP-200 Replace select precursor

apps/epp-replace/translations/src/en/fields.json
[EPP-284](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-284) - Fix page where it was not matching the figma design exactly for  Replace - EPP
=> EPP-284 Fix new address bug

apps/epp-replace/translations/src/en/validation.json
[EPP-288](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-288) - fix validation error messages in new address - Replace - EPP
=> EPP-288 Correct validation message bug

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/content/amend-details-content.md, apps/epp-amend/views/no-details-amend.html, apps/epp-common/behaviours/aggregator-save-update-precursors-poisons.js, apps/epp-common/behaviours/modify-summary-change-links.js, apps/epp-common/behaviours/parse-summary-precursors-poisons.js, apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, test/unit/behaviours/aggregator-save-update-precursors-poisons.spec.js
Create poisons details page for replace journey as per jira ticket [EPP-205](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-205)
to allow user to provide details about the selected poison
- add step in index.js and configured RenderPoisonDetails behaviour
- add fields in : fields/index.js, fields.json, pages.json, validations.json 
manual
=> EPP-205 replace - POISON DETAILS

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/select-poisons.html
Add a select poison page to the form as per jira ticket [EPP-88](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-88)
to allow user to add poison from dropdown menu
- add select-poison step to `index.js` 
- add `select-poison.html`
- add "/select-poison" page content to `page.json` 
- add ` poison-field` to 
* fields/index.js, 
* fields.json 
* validation.json
manual test
=> EPP-88 create select poison page

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json
Add to form the poison detail page as per ticket [EPP-89](https://collaboration.homeoffice.gov.uk/jira/secure/RapidBoard.jspa?rapidView=4360&projectKey=EPP&view=detail&selectedIssue=EPP-89#:~:text=Ready,-for%20Test)
to allow user to provide information about the poison storage and percentage for which is apply for licence
- add step and fields to `index.js`
- add fields to 
* `fields/index.js`,
* ` pages.json`, 
* `fields.json`, 
* `validation.json`
configured behaviours mirroring amend journey
manual 
=> EPP-89 Poison Details page for new renew journey

apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/pages.json, apps/epp-new/views/partials/aggregator-summary-table.html, apps/epp-new/views/precursors-summary.html
create a precursor summary page as per Jira ticket [EPP-87](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-87)
to allow user to review the precursors' information provided before continuing and submit the form.
- add precursor summary step to `index.js` and `summary-data-section.js`
- add content to `pages.json`
- add view `precursors-summary.html`
manual test
=> EPP-87 new-renew PRECURSOR SUMMARY

apps/epp-amend/translations/src/en/fields.json, apps/epp-new/translations/src/en/fields.json, apps/epp-replace/translations/src/en/fields.json
Bug fixing as per jira ticket [EPP-297](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-297)
On all journeys, when user is on the mid-summary page, when they add 2 or more items there is a bug which changes the previous item name and matches it with the most recent one added.
As per agreement with PM and DM, the labels for mid-summary pages for precursors and poisons are now hard coded.
- tide up `field.json` using the page flow order.
- update amend, replace and new-renew journeys, poisons and precursors  `.summary-heading` for following fields:
* where-to-use-precursor + poison
* why-need-precursor + poison
* where-to-store-precursor + poison
Manual test
=> EPP-297 bug fix all journeys

kube/html-pdf/html-pdf-deployment.yml
* Using html-pdf-converter image with Node v 22 and upgraded node packages
* Tested and replaced in all the remaining HOF services
* Fixed vulnerabilities in the image
* Testing in Branch env
* https://collaboration.homeoffice.gov.uk/jira/browse/EPP-282
* Large number of Critical and High CVE Vulnerabilities have been detected by Trivy Scan
* Node image v18 is outdated. HOF is moving to v20 and v22 in future Goals.
* Replace html-pdf-converter image with latest
* Add a comment to explain the version and Date.
* Regression testing in Branch and then merge to master to deploy and test in UAT, Stage and promote to Prod
* Check boxes will ticked as we pass through each env
* Drone build is successful
* Pods are Healthy
* Staging environment has been commented out in pipeline 4 years ago by …
=> EPP-282: Update html-pdf-converter image to latest v3.0.0

apps/epp-amend/behaviours/countersignatory-navigation.js, apps/epp-amend/index.js, apps/epp-common/behaviours/reset-section-summary.js, apps/epp-new/index.js, apps/epp-replace/behaviours/no-precursors-poisons-navigation.js, apps/epp-replace/behaviours/no-substance-change-navigation.js, apps/epp-replace/index.js, test/unit/behaviours/reset-section-summary.spec.js
Bug fix as per jira ticket [EPP-300](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-300)
On the check your answers page for the replace flow, when the user has previous answer yes to explosive precursors and filled in the corresponding information, when they change the answer to no then the information on EP should be removed. However, the information regarding EP is not removed from the check your answers page.
Update : 
reset-section-summary behaviour and related unit test
updated
=> epp-300 bug fix

kube/redis/redis-deployment.yml
* Following changes has been done to Redis image
*  Upgraded Redis from 5.0.6 to 7.0.15 and tagged image accordingly.
*   Switched base image from Fedora to Rocky Linux 9.3 due to Trivy support.
*  Done sanity checks on EPP and is working as expected.
*  Refer to https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-1232
* Further information added to description of Jira ticket
**Upgrading Redis to 7.0.15**
Security Fixes: Redis 5.0.6 is quite old and has known vulnerabilities. Upgrading to 7.0.15 ensures you're protected against those and benefits from the latest security patches.
Performance Improvements: Newer Redis versions often include performance optimizations and bug fixes that improve stability and efficiency.
Feature Enhancements: Redis 7.x introduces new features like ACL …
=> HOFF-1232: Use latest Redis Docker image with fixed vulnerabilities
