UKHomeOffice/explosives-precursors-poisons

.drone.yml, Dockerfile, bin/clean_up.sh, bin/deploy.sh, bin/sanity_check_build.sh, kube/app/deployment.yml, kube/app/ingress-external.yml, kube/app/ingress-internal.yml, kube/app/networkpolicy-external.yml, kube/app/networkpolicy-internal.yml, kube/app/service.yml, kube/certs/certificate-external.yml, kube/certs/certificate-internal.yml, kube/configmaps/configmap.yml, kube/redis/redis-config.yml, kube/redis/redis-deployment.yml, kube/redis/redis-network-policy.yml, kube/redis/redis-service.yml, run.sh
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-4 
Creation of a new service - envs and secrets and namespace and 
Adding files and folders necessary to deploy into environments via CI/CD pipeline.
This is the first initial setup of Kubernetes with its secrets the service can be deployed into the namespaces.
Adding the right configs and kube files
WIP
=> EPP-4 set up of namespaces and envs

.drone.yml, README.md
Jira ticket [EPP-117](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-117) it is a tech ticket to fix a double build when we push a change in a branch that has an open PR
To avoid double build when push occurs 
update `drone.yaml`
n/a
=> [tech] fix double build

.drone.yml
[EPP-67](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-67) adding config to drone deploy to uat
Move deployments into uat
=> EPP-67 adding deploment to uat

.drone.yml
* Cron jobs has been added to Drone
* These cron steps will trigger on scheduled time
* Cron steps scan for vulnerabilities and also delete deployments created by pull requests
* Work done as part of the Jira ticket https://collaboration.homeoffice.gov.uk/jira/browse/EPP-99
* We need Security scanners to scan and publish the vulnerability reports in Drone CI
* If there is any failed Cron jobs we will see the notifications in Slack
* We have also added tear down pr envs. These are the deployment objects in kubernetes that are deployed by Drone with Pull requests. 
* Tear down pr envs will help us keep costs and expenditures down 
* Cron jobs feature in Drone will be helpful to run required steps as per the scheduled time similar to cron tasks in Linux
* We futher test the notification in …
=> EPP-99: Add Cron Steps to pipeline

apps/epp-amend/behaviours/licence-validator.js, apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-common/index.js
[EPP-60](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-60) - Amend - SEC5 - Create a what are your CONTACT DETAILS page.
According to figma design to allow user provide contact details 
- Added email address and phone number fields in the field index.js
- Added validation for each field
- Displayed the values of each fields in the summary page
Tested on locally machine 
=> EPP 60 Contact details

apps/epp-new/behaviours/section-counter.js, apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/medical-declaration.html
Create a MEDICAL DECLARATION page for new and renew page
as per jira business request ticket specifications [EPP-74](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-74)
-add fields in :
- fieds/index.js,
- page.json,
- field.json,
- new/index.js
- add sections in summary-data-sections.js
- add validation.json
- add some content in pages.json
- create a custom html page
manual
=> EPP-74-New and Renew medical-declaration

utilities/helpers/index.js
[EPP-144](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-144) - Spaces allowed
When User enter Licence number with space system will not allow.
- Added a regex to remove space within text
manual test
=> EPP 144 Bug fix to remove space

utilities/constants/countries.js
[EPP-140](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-140) - Add countries to countries list
It has been identified that there were two countries missing (South Sudan and Côte d'Ivoire) from the list of countries
=> EPP-140 Updated countries list

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/criminal-record.html
[EPP-71](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-71) - Create criminal record page for new & renew flow - EPP
Allows user to select if they are a dependant or a guardian of a dependant
- Added HTML file for static content
- Added radio buttons
=> EPP-71 Create criminal record page

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/amend-details.html, apps/epp-amend/views/content/amend-details-content.md, assets/scss/app.scss
[EPP-62](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-62) - Amend - SEC6 - Create a AMEND LICENCE DETAILS page
According to Figma design to allow user decide if they want to amend there details
- Added fields to page
- Added validation controller and error messages to the field
- Added markdown file to display content on the page
- Added field value to the confirmation page
- Added routes
manually 
=> EPP 62 AMEND LICENCE DETAILS

apps/epp-amend/index.js
quick fix update logic with correct value of comparison.
to test branch tears down correctly
To assure  the correct redirection if `UK-passport` is selected 
update `amend/ index.js`
manual test
=> EPP-101 quick fix

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, test/unit/utilities/utilities.spec.js, utilities/helpers/index.js, utilities/helpers/postcode-validation.js
[EPP-40](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-40) - New & Renew - Create a HOME ADDRESS page
Home address page for new and renew flow
- Created home address page for new and renew flow
- Refactored post code validator for reusability across 3 forms
- Added helper for abstraction 
=> EPP-40 Home Address Page

apps/epp-amend/behaviours/after-date-validator.js, apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-common/behaviours/after-date-validator.js, apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, test/unit/behaviours/after-date-validator.spec.js, test/unit/utilities/utilities.spec.js, utilities/helpers/index.js, utilities/helpers/move-date-validator.js, utilities/helpers/postcode-validation.js
[EPP-77](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-77) -  Amend - SEC7 - Create a WHAT IS YOUR NEW NAME page
To Allow applicant provide new name 
- Added fields name and properties
- Added validation behaviour to check if date of birth after amend new date
-  Added values to summary page
tested manually 
=> Epp 77 amend  what is your name

kube/app/deployment.yml, kube/file-vault/file-vault-deployment.yml
* Env Variables used by file vault container are incorrect and they have been replaced
* Secret key ref are using incorrect keys and they have been corrected
* File Vault image tag is incorrect. Now is using the one used by all HOF services
* Conditions applying configs to all the env are added back
* 
* Fixes issue
`"code":"UNKNOWN","level":"error","message":"Failed to save document: Error: File upload failed: Keycloak username is not defined Failed to save document: Error: File upload failed: Keycloak username is not defined","stack":"Error: Failed to save document: Error: File upload failed: Keycloak username is not defined\n  at FormController.saveValues (/app/apps/epp-common/behaviours/save-document.js:73:23)\n  at process.processTicksAndRejections `
* Few unidentified issues has …
=> EPP-165: Fix Fileupload issues and keycloak authentication issues

config.js
quick fix
config.js file contained a misplaced bracket. 
add the curly bracket in the right place.
verify the build in drone c/i
=> Quik fix EPP 103

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/explosives-precursors.html
[EPP-124](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-124) - Create a EXPLOSIVES PRECURSORS page
Users can select whether they need to amend the explosives precursors on your licence.
=> EPP-124 Amend - Explosives precursors page

apps/epp-common/behaviours/save-document.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/medical-form.html, assets/js/index.js, config.js
[EPP-76](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-76) - New & Renew - Create an UPLOAD MEDICAL FORM page
- Users can upload the medical form if required
- Create upload page
- Added required validation and content
- Fixed a bug around disabling continue and upload items while file is being uploaded
=> EPP-76 Upload medical form

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/translations/src/en/buttons.json, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/declaration.html
[EPP-173](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-173) - Amend - declaration page
- Users can and agree to the declaration
- Page created with required content and validation
=> EPP-173 amend declaration page

apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/birth-certificate.html, config.js
add upload birth certificate page
to allow user to upload the birth certificate to Countersignatory documents if user is under 18.
- add page for amend birth-certificate.html
- add fields in summary data-sections.js
- page.json and validation.json
- add file upload limit in config.js
manual
=> EPP-211 upload birth certificate

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-amend/views/select-poisons.html
create select poisons pages as per jira ticket [EPP-169](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-169)
To allow user to select a poison from list
- add field in index.js, fields/index.js, fields.json, pages.json, validation.json 
- add select-poisons.html
- add section to summary data section
manual
=> EPP-169 select poisons

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json
[EPP-184](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-184) - Create What is your name page for Replace - EPP
Allows user to enter name that's on their licence
=> EPP-184 Create what is your name page for Replace

apps/epp-common/index.js, apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json
[EPP-213](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-213) - Create Why do you need to replace page for REPLACE - EPP
Allows user to select why they need a replacement
- Added Heading and radio buttons for page
=> EPP-213 Why do you need to replace page

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/select-poisons.html
create page to select poison for replace journey as per jira ticket [EPP-204](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-204)
to allow user to select the poisons from the dropdown menu
- add field in fields/index.js, page.json, validation.json, fields.json
- update index.js and summary-data-selections -add select-poisons.html
manual
=> EPP-204 replace select poison

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/must-report-theft.html
[EPP-214(https://collaboration.homeoffice.gov.uk/jira/browse/EPP-214) - Create Have you reported page for New & Renew - EPP
Allows user to report if it has been reported to the police
- Added Heading and radio buttons for page
=> EPP-124 Create Have you reported page

apps/epp-amend/translations/src/en/validation.json, apps/epp-new/translations/src/en/validation.json, apps/epp-renew/translations/src/en/validation.json, apps/epp-replace/translations/src/en/validation.json
For url validation, we seem to have two versions of the error message
- Your answer must not include a URL 
- Answer must not contain a URL. Remove any links, URLs or special characters like /@:%_+~#=\\ from your answer
UCD confirmed that we should use 2nd option across the application
To have consistent error message across the application
local and branch testing
=> EPP-223 Updated not url validation error message

apps/epp-common/behaviours/initiate-payment-request.js, config.js, package.json, test/unit/utilities/api.spec.js, test/unit/utilities/crypto-random-string.spec.js, utilities/helpers/api.js, utilities/helpers/crypto-random-string.js, yarn.lock
[EPP-257](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-257) - Add GovPay Reference and Description
To filter or search transactions based on the reference number
Payment description and reference are added
local and branch testing
=> EPP-257 Payment summary and ref

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json
[EPP-185](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-185) - Create What is your dob page for Replace - EPP
Allows user to enter dob 
=> EPP-185 Replace What is your dob page

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json
[EPP-94](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-94) - Create Countersignatory id page - New Renew - EPP
Allows user to enter countersignatory ID
=> EPP-94 Create Countersignatory id page - New Renew

apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/validation.json
[EPP-261](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-261) - bug fix for title and error message for new-renew (EPP-94) - EPP
Incorrect error message
- fixed title
- fixed validations
=> EPP-261 bug fix for title and error message

apps/epp-amend/fields/index.js, apps/epp-new/fields/index.js, apps/epp-renew/fields/index.js, apps/epp-replace/fields/index.js
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-259
Following a discussion with UCD, we have identified some inconsistencies in label sizing across the three forms
=> EPP-259 Standardize labels

apps/epp-replace/index.js, apps/epp-replace/translations/src/en/fields.json
[EPP-275](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-275) - fix bugs for EPP190r Replace - EPP
Fixed bug which didn't show hint text
Fixed no section number also
- Fixed bug which didn't show hint text
- Fixed no section number also
=> EPP-275 Fix bug for EPP-190

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/translations/src/en/buttons.json, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/declaration.html, apps/epp-replace/views/payment-cancelled.html, apps/epp-replace/views/payment-failed.html, apps/epp-replace/views/payment-problem.html, utilities/helpers/notify-helpers.js
GOV Pay payment integration for replace journey
Associated tickets:
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-233
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-235
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-236
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-237
Users can complete the payment for replacing their licence
Declaration and error pages created
Integrated existing behaviour for initiating and validating the payment
Payment core changes can be seen [here](https://github.com/UKHomeOffice/explosives-precursors-poisons/pull/88)
=> EPP-233 Replace - Payment Integration

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, config.js
[EPP-186](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-186) - Create What is your name page for Replace - EPP
Allows user to enter their home address
=> EPP-186-Replace create Home address page

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, utilities/constants/police-forces.js
[EPP-215](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-215) - Create a CRIME REPORT DETAILS page
To allow users to enter the crime details. 
- Configured the list of police forces
- Page created with required content and validation
=> EPP-215 crime report details page

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, config.js, utilities/helpers/postcode-validation.js
[EPP-83](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-83) - Doctor details page
To allow users to enter their doctor's details
Page created with required content and validation
Refactored post code validator - consolidated related logic within the behaviour 
=> EPP-83 Doctor detail page

apps/epp-amend/fields/index.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/validation.json
Fixed some of the issues identified during manual testing
- Legend and hint text updated for counter signatory id pages
- Updated incorrect legend class
- Updated incorrect error message for change your name page
- Added typeahead classes to countries select box
=> EPP-223 Updated text, error and classes

apps/epp-common/behaviours/no-precursor-poison-navigate.js, apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-new/views/poisons.html, test/unit/behaviours/no-precursor-poison-navigate.spec.js
[EPP-218](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-218) -  Regulated poisons page
Whether the licence need to cover poisons.
- Page created with required validation and content
- Created custom behaviour to handle the navigation
- Unit tests
=> EPP-218 Regulated poisons page

apps/epp-replace/behaviours/navigate-no-changes.js, apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/change-substances.html
[EPP-198](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-198) - Create change in substances page for Replace - EPP
Allows user to enter if they have a change in substance
- HTML
=> EPP-198 create change in substances page

apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/pages.json, apps/epp-common/behaviours/get-payment-info.js, apps/epp-common/behaviours/save-home-other-address.js, apps/epp-common/behaviours/save-new-name.js, apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/translations/src/en/journey.json, apps/epp-new/translations/src/en/pages.json, apps/epp-replace/index.js, test/unit/behaviours/save-home-address.spec.js, test/unit/utilities/notify-helpers.spec.js, test/unit/utilities/utilities.spec.js, utilities/constants/string-constants.js, utilities/helpers/index.js, utilities/helpers/notify-helpers.js
[EPP-182](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-182) - Finalise the CHECK YOUR ANSWERS page
- Updated content on confirm page
- Added and updated notify fields
- Added JSDoc and unit tests
- Added helper to format attachment and display optional fields
=> EPP-182 Amend check your answers and notify updates

apps/epp-new/index.js, apps/epp-new/sections/summary-data-sections.js, apps/epp-new/views/no-poisons-or-precursors.html, apps/epp-replace/behaviours/navigate-no-changes.js, apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/change-substances.html, test/unit/models/file-upload.spec.js
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-220
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-219
- Above two pages are created to these can be tested within the same flow
- Pages are created with required validation and content
- Added new behaviour for back link
- Added unit tests
=> Epp 220 Do not need licence & explosives precursors pages

apps/epp-amend/index.js, apps/epp-common/behaviours/counter-signatory-navigation.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/views/partials/aggregator-summary-table.html, apps/epp-replace/views/partials/summary-table.html, apps/epp-replace/views/poison-summary.html, test/unit/behaviours/counter-signatory-navigation.spec.js
[EPP-206](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-206) - POISONS ON YOUR LICENCE page
To display the summary of selected poison details 
=> EPP-206 Poison summary page

apps/epp-common/translations/src/en/fields.json
[EPP-256](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-256) - Change the content of the start page
Labels updated to
- Renew a licence
- Replace a licence
=> EPP-256 Content changes

apps/epp-amend/behaviours/countersignatory-navigation.js, apps/epp-amend/index.js, test/unit/behaviours/countersignatory-navigation.spec.js
Fixed the navigation to the counter signatory details page - amend journey. 
- Added a custom behaviour
=> Fix amend counter signatory navigation

apps/epp-amend/fields/index.js, apps/epp-amend/index.js, apps/epp-amend/sections/summary-data-sections.js, apps/epp-amend/translations/src/en/fields.json, apps/epp-amend/translations/src/en/pages.json, apps/epp-amend/translations/src/en/validation.json, apps/epp-common/behaviours/aggregator-save-update-precursors-poisons.js, apps/epp-common/behaviours/modify-summary-change-links.js, apps/epp-common/behaviours/parse-summary-precursors-poisons.js, apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/precursors-summary.html, test/unit/behaviours/aggregator-save-update-precursors-poisons.spec.js
- https://collaboration.homeoffice.gov.uk/jira/browse/EPP-201
- https://collaboration.homeoffice.gov.uk/jira/browse/EPP-202
Added precursor summary and details page
=> EPP-202, 201 - Replace precursor details and summary pages

apps/epp-new/fields/index.js, apps/epp-new/index.js, apps/epp-new/translations/src/en/fields.json, apps/epp-new/translations/src/en/pages.json, apps/epp-new/translations/src/en/validation.json, apps/epp-replace/index.js, utilities/helpers/notify-helpers.js
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-86 - Precursor details page
- Page added with required content and validation 
- check your answers page will be updated as part of section summary page
=> EPP-86 precursor details page

apps/epp-replace/index.js, test/unit/utilities/notify-helpers.spec.js, utilities/helpers/notify-helpers.js
- Updated fields mapping for replace flow as most of the fields are now available. Will need to add the remaining fields when all pages are completed. 
- Removed redundant route/page
=> EPP-106 replace notify fields mapping

apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/explosives-precursors.html
[EPP-199](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-199) - Create explosive precursor page for Replace - EPP
Allows user to decide if they need to amend the poison on their licence
=> EPP-199 Replace Explosive precursor page

apps/epp-common/behaviours/reset-section-summary.js, apps/epp-replace/behaviours/no-precursors-poisons-navigation.js, apps/epp-replace/behaviours/no-substance-change-navigation.js, apps/epp-replace/fields/index.js, apps/epp-replace/index.js, apps/epp-replace/sections/summary-data-sections.js, apps/epp-replace/translations/src/en/fields.json, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/translations/src/en/validation.json, apps/epp-replace/views/poisons.html, test/unit/behaviours/no-substance-change-navigation.spec.js, test/unit/behaviours/reset-section-summary.spec.js, utilities/helpers/notify-helpers.js
https://collaboration.homeoffice.gov.uk/jira/browse/EPP-203 - REGULATED POISONS page
Allow users to select whether they need to amend the poisons on their licence
- Created the page with required content and behaviour
- Added behaviour to handle the navigation
- tidy up the confirm page
=> EPP-203 regulated poisons page

apps/epp-amend/translations/src/en/pages.json, apps/epp-new/translations/src/en/pages.json
checked new and renew confirm summary page as per jira ticket [EPP-95](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-95)
to fix typos and incorrect naming
- update page.json
manual
also update amend flow.
=> EPP-95 tide up new-renew

apps/epp-replace/translations/src/en/pages.json
[EPP-238](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-238) - Finalise the confirm page for Replace - EPP
Make sure it matches the figma
- Compared figma to my local
=> EPP-238 Finalise confirm page for replace

apps/epp-replace/translations/src/en/validation.json
[EPP-184](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-199) - Fix error bug message for Replace - EPP
Incorrect error message
=> EPP-199-Bug fix validation error message

apps/epp-amend/views/pdf.html, apps/epp-new/views/pdf.html, apps/epp-replace/views/pdf.html, assets/scss/app.scss
Final tidy up of the PDF formatting.
Final tidy up of the PDF linked to business notify email to check it displays per design and account for small changes. As per Jira ticket [EPP-250](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-250)
update pdf.html for all journeys:
- new-reniew
- amend
- replace
manual test
=> EPP-250 fix PDF layout

apps/epp-amend/views/pdf.html, apps/epp-new/views/pdf.html, apps/epp-replace/views/pdf.html, assets/scss/app.scss
Tech quick fix 
update pdf.html for all journeys:
new-reniew
amend
replace
=> EPP-250 rename class

apps/epp-common/behaviours/get-payment-info.js, apps/epp-new/index.js, apps/epp-new/translations/src/en/pages.json, apps/epp-new/views/service-problem.html, apps/epp-replace/index.js, apps/epp-replace/translations/src/en/pages.json, apps/epp-replace/views/service-problem.html, kube/html-pdf/html-pdf-deployment.yml, test/unit/behaviours/get-payment-info.spec.js, utilities/constants/string-constants.js
Customise error message for Gov Notify scenario
As per jira ticket  [EPP-239](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-239)
-add service-problem.html page for new-renew and replace journeys 
-add content in pages.json for new-renew and replace journeys 
-update submit-notify.js
=> EPP-239 notify service problem

apps/epp-amend/views/layout.html, apps/epp-common/views/layout.html, apps/epp-new/views/layout.html, apps/epp-renew/views/layout.html, apps/epp-replace/views/layout.html
=> EPP Change layout code

test/unit/utilities/notify-helpers.spec.js, utilities/helpers/notify-helpers.js
update the email content as per jira ticket [EPP-283](https://collaboration.homeoffice.gov.uk/jira/browse/EPP-283)
since business requirement 
applied `formatSectionSummaryItems` method to explosive and poison notify variables.
- update `notify.js` helper
manual test
=> EPP-283 email refinement
